### ISSUE TITLE
Deploy Apex stack on OpenShift AWS

### ISSUE THREAD

**Issue by vishnoianil** [redhat-et/apex#178]
Let's attempt to deploy our SaaS stack on OpenShift AWS.

**Comment by russellb** [comment]
@vishnoianil complete (or maybe obsolete) by the work on operate-first?

**Comment by vishnoianil** [comment]
@russellb Yes, There is no plan to deploy it on openshift AWS as such, given that we have the Apex SaaS running on operate first cloud. I think the same manifest file can be used for openshift AWS as well. So we can close this issue.
