### ISSUE TITLE
kustomize: Add operate-first overlay

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/apex#212]
Add an overlay for operate-first (copy the dev one and change hostname overrides)

This should include a `production` dex config.
Related to https://github.com/operate-first/support/issues/1154

Since we'd require the use of `externalsecrets` to securely store credentials used for GitHub authentication.

**Comment by russellb** [comment]
@dave-tucker I think this is complete. Is there anything else you want to track with this?
