### ISSUE TITLE
Investigate timeout of agent auth 

### ISSUE THREAD

**Issue by nerdalert** [redhat-et/apex#248]
Issue: After a day or two of an api-server running, connected agents are no longer authorized and hit 401s on peer listing polls. Re-joining will resolve the issue which indicates its auth related. 

api-server logs:

```
2022-12-14T02:29:17.387Z	DEBUG	routers/middleware.go:44	verifying token
[GIN] 2022/12/14 - 02:29:17 | 401 |     237.251µs |      10.244.0.7 | GET      "/zones/407e2a23-3cf1-497d-a1c6-1f87dd376d84/peers"
2022-12-14T02:29:17.539Z	DEBUG	routers/middleware.go:44	verifying token
[GIN] 2022/12/14 - 02:29:17 | 401 |     119.834µs |      10.244.0.7 | GET      "/zones/407e2a23-3cf1-497d-a1c6-1f87dd376d84/peers"
2022-12-14T02:29:17.836Z	DEBUG	routers/middleware.go:44	verifying token
[GIN] 2022/12/14 - 02:29:17 | 401 |     133.175µs |      10.244.0.7 | GET      "/zones/407e2a23-3cf1-497d-a1c6-1f87dd376d84/peers"
```

It may be the `idTokens: "24h"` in Dex expiring and not getting refreshed.

**Comment by dave-tucker** [comment]
My theory is:
- We use the refresh token... but when we exchange it for an id_token, we don't also get another refresh token

This should be pretty easy to test by changing the idToken validity in the dex config to `10m`, which is actually recommended security practice anyway.
