### ISSUE TITLE
Markdown lint is too greedy!

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/apex#432]
### Describe the bug

I ran `make all` and was overrun with markdownlint warnings.

### How to Reproduce

Do some development on the UI, which populates `./ui/node_modules` and then the lint will never pass.

### Expected Behavior

The lint should only check docs that are under our control (i.e not paths that are .gitignored).

**Comment by russellb** [comment]
Weird. I thought I had it set to ignore node_modules. Check out the command. https://github.com/redhat-et/apex/blob/main/Makefile#L83

I’ll take a look

**Comment by dave-tucker** [comment]
to quickly reproduce
```bash
mkdir -p ui/node_modules
echo "[@]()" > ui/node_modules/foo.md
make mardown-lint
```

outputs:
```
ui/node_modules/foo.md:1:1 MD042/no-empty-links No empty links [Context: "[@]()"]
make: *** [Makefile:83: markdown-lint] Error 1
```
